(function(){
"use strict";
var routes=["/about","/feedback","/reviews","/complaints","/disputes","/refund-policy","/access"];
var receiver="ceo@rosstaxsoftware.com";
function link(path,label,style){return '<a data-route href="'+path+'" class="'+(style||"btn btn-outline")+'">'+label+'</a>';}
function title(h,p){return '<section class="pagehead"><div class="wrap"><div class="eyebrow">R-RENT • CUSTOMER EXPERIENCE</div><h1>'+h+'</h1><p>'+p+'</p></div></section>';}
function panel(h,p,action){return '<article class="care-tile"><h3>'+h+'</h3><p>'+p+'</p>'+action+'</article>';}
function about(){return title("About R-Rent","Purposeful mobility, clear expectations and a responsible independent rental experience.")+
'<section class="section"><div class="wrap"><div class="eyebrow">WHO WE ARE</div><h2>Drive More. Go Further.</h2><p class="care-lead">R-Rent is the company-operated vehicle rental division of Ross Tax Pro Software Company, serving the Central Texas area. We are developing an independent direct-rental experience—not affiliated with Turo.</p><div class="grid three">'+panel("Our commitment","Transparent quotes, disclosed terms, and clearly separated optional add-ons.",link("/fees","View fees"))+panel("Our fleet","2026 Chevrolet Trailblazer and 2026 Ford Bronco Sport Big Bend; actual availability remains manually confirmed.",link("/fleet","Explore vehicles"))+panel("Our standard","Authorized staff review driver, insurance and agreement requirements before vehicle release.",link("/requirements","Review eligibility"))+'</div></div></section>'+
'<section class="section alt"><div class="wrap care-story"><div><div class="eyebrow">FOUNDER & BRAND AMBASSADOR</div><h2>Andreaa Chan’nel</h2><p>R-Rent extends Ross Tax Pro Software Company’s service philosophy into the vehicle-rental experience. The division is structured to prioritize accountability, communication, and documented procedures.</p><p class="subtle">Photography will be published only when an approved owner image is available; this page does not substitute an AI-generated likeness.</p></div><div class="care-mark care-textmark" role="note"><strong>R-RENT</strong><span>Approved owner photography pending</span></div></div></section>'+
'<section class="section"><div class="wrap care-actions">'+link("/book","Estimate a rental","btn btn-wine")+link("/contact","Contact R-Rent","btn btn-outline care-dark")+link("/refund-policy","Read cancellation and refund policy","btn btn-outline care-dark")+'</div></section>';}
function policy(){return title("No-refunds & cancellation policy","Our proposed standard for disclosed rental charges, subject to final contract review and applicable law.")+
'<section class="section"><div class="wrap care-prose"><div class="notice"><strong>Policy status: draft pending Texas legal/insurance approval.</strong> This website does not currently accept reservations or payments. No non-refundable fee is charged by this preview site.</div>'+
'<h2>1. General non-refundable rental charges</h2><p>After a reservation is lawfully confirmed and the customer has clearly accepted the final price and cancellation terms, rental-day charges and separately disclosed reservation or administrative fees may be designated non-refundable to the extent permitted by the applicable agreement and law. Nothing on this page makes an undisclosed fee non-refundable or creates a booking before confirmation.</p>'+
'<h2>2. Cancellation and unused rental time</h2><p>A customer must request cancellation or shortening of the rental according to the issued agreement. Whether any base rental payment is refundable depends on the final disclosed contract, the timing and circumstances, and applicable law. No automatic promise of a refund or forfeiture is made for unconfirmed reservations. Extensions require a new approved price and valid insurance period.</p>'+
'<h2>3. Mandatory exceptions</h2><p>Notwithstanding a general no-refunds rule, R-Rent will process refunds or adjustments required by law, including qualifying unused damage-waiver charges under Texas Business &amp; Commerce Code §91.057, mistaken or duplicate charges, refunds owed for services not delivered, and other legally required corrections. Optional damage waivers must be separately elected; they are not automatically bundled into rental charges.</p>'+
'<h2>4. Deposits and authorization holds</h2><p>Security deposits and payment-card authorization holds are not automatically earned rental revenue and are not covered by a blanket no-refunds rule. Release or return follows the disclosed terms, documented legitimate deductions, processor/card-network rules, and applicable law. Financial institutions may control posting times.</p>'+
'<h2>5. Charge inquiries and disputes</h2><p>Renters may request an itemized charge explanation, contest damage or additional charges, report incorrect billing, or exercise rights with their card issuer. This policy does not waive statutory rights or block chargebacks. Each disputed amount will be reviewed with documented evidence by authorized personnel.</p>'+
'<h2>6. When customers see these terms</h2><p>Before collecting payment, the final checkout must show the exact base rental rate, mandatory charges, taxes, refundable holds, optional selections, deadlines and a distinct acknowledgment of any non-refundable amount. The issued rental agreement—not this pre-launch summary—will contain the operative contract revision after counsel approval.</p>'+
'<div class="care-actions">'+link("/disputes","Dispute a charge","btn btn-wine")+link("/fees","View fee index","btn btn-outline care-dark")+'</div><p class="subtle">Legal reference: Texas Business &amp; Commerce Code Chapter 91, including §§91.055 and 91.057. Final policy requires professional review.</p></div></section>';}
function contact(){return title("Contact R-Rent","Questions, service concerns and billing issues have different paths to get the right review.")+
'<section class="section"><div class="wrap"><div class="grid three">'+panel("General assistance","Questions about fleet models, business information or a proposed rental. Do not email driver’s license images, SSNs or payment card numbers.",'<a class="btn btn-wine" href="mailto:'+receiver+'?subject=R-Rent%20General%20Inquiry">Compose email</a>')+panel("File a complaint","Document a service issue and prepare a written report for staff review.",link("/complaints","Complaint form","btn btn-wine"))+panel("Dispute a charge","Request an itemized billing review and challenge a rental charge.",link("/disputes","Charge dispute","btn btn-wine"))+'</div><div class="notice">The displayed address is the company’s existing executive contact, not a confirmed staffed rental-support queue. Do not send sensitive IDs, insurance declarations, bank details, or complete card numbers by ordinary email. A secure ticket portal is gated pending production authentication and records storage.</div><div class="care-actions">'+link("/feedback","Share feedback","btn btn-outline care-dark")+link("/reviews","Customer reviews","btn btn-outline care-dark")+'</div></div></section>';}
function serviceForm(kind){var dispute=kind==="disputes",feedback=kind==="feedback",review=kind==="reviews";
var h=dispute?"Dispute a rental charge":feedback?"Give R-Rent feedback":review?"Customer reviews":"File a service complaint";
var p=dispute?"Request an explanation or correction of a transaction without giving up your rights with your card issuer.":feedback?"Tell us what went well and what could improve.":review?"We do not publish fabricated ratings or selectively exclude genuine negative reviews.":"Document a concern and ask for a human review.";
var c=review?'<div class="notice">No authenticated customer reviews are published yet. Reviews must reflect actual experiences; ratings will not be invented or generated as testimonials.</div>':"";
var options=dispute?'<option value="Incorrect amount">Incorrect amount</option><option value="Duplicate charge">Duplicate charge</option><option value="Unauthorized charge">Unauthorized charge</option><option value="Deposit or hold">Deposit or hold</option><option value="Additional fee">Additional fee</option><option value="Other billing concern">Other billing concern</option>':feedback?'<option value="Website experience">Website experience</option><option value="Vehicle selection">Vehicle selection</option><option value="Service experience">Service experience</option><option value="Other feedback">Other feedback</option>':review?'<option value="5 stars">5 stars</option><option value="4 stars">4 stars</option><option value="3 stars">3 stars</option><option value="2 stars">2 stars</option><option value="1 star">1 star</option>':'<option value="Customer service">Customer service</option><option value="Vehicle condition">Vehicle condition</option><option value="Agreement or charges">Agreement or charges</option><option value="Safety or incident">Safety or incident</option><option value="Other concern">Other concern</option>';
return title(h,p)+'<section class="section"><div class="wrap care-form-shell"><div class="care-paper">'+c+'<h2>Prepare a written request</h2><p class="subtle">This public form prepares a draft on your device. It does not file a case automatically. Do not enter private ID numbers, account/card numbers, or insurance policy documents.</p>'+
'<form id="care-intake" data-kind="'+kind+'"><div class="formgrid"><div class="field"><label for="case-type">Category</label><select id="case-type" required><option value="">Choose a category</option>'+options+'</select></div><div class="field"><label for="case-ref">Rental reference (optional)</label><input id="case-ref" maxlength="48" placeholder="Reference only — no ID numbers" autocomplete="off"></div></div>'+
(dispute?'<div class="formgrid care-row"><div class="field"><label for="case-amount">Disputed amount (USD, optional)</label><input type="number" id="case-amount" min="0" max="999999" step="0.01" placeholder="0.00"></div><div class="field"><label for="case-date">Transaction date (optional)</label><input type="date" id="case-date"></div></div>':'')+
'<div class="field care-row"><label for="case-description">Details</label><textarea id="case-description" rows="6" minlength="15" maxlength="3000" required placeholder="Explain what happened and what outcome you are requesting. Avoid sensitive account, ID and card details."></textarea></div><label class="care-check"><input type="checkbox" id="care-understand" required> I understand this creates an email draft and does not submit a ticket until I send it.</label>'+
'<div class="care-actions"><button class="btn btn-wine" type="submit">Prepare email request</button><button class="btn btn-outline care-dark" type="button" id="copy-case" disabled>Copy drafted request</button></div><p id="care-result" role="status" aria-live="polite" class="subtle"></p></form>'+
'<div class="notice"><strong>Protected filing gate:</strong> Authenticated, evidence-backed case submission is not yet enabled. Do not assume an internal case number exists from this draft. For an urgent safety issue contact appropriate local emergency services.</div></div><aside class="care-aside"><h3>What happens next</h3><ol><li>Prepare the issue with the relevant rental reference and a clear explanation.</li><li>Use your email program to send the draft; retain a copy.</li><li>Authorized staff must acknowledge and investigate under the applicable operational process.</li><li>Once the protected case portal is active, authenticated submission and tracking will be available.</li></ol>'+
(dispute?'<p><strong>Cardholder rights:</strong> You can also contact your card issuer directly. For qualifying credit-card billing errors, additional written-notice deadlines may apply.</p>':'')+
'<div class="care-actions">'+link("/refund-policy","Refund policy","btn btn-outline care-dark")+link("/contact","Contact","btn btn-outline care-dark")+'</div></aside></div></section>';}
function access(){return title("Secure customer access","OAuth sign-in, identity verification and role-based controls are planned but gated until provider configuration is verified.")+
'<section class="section"><div class="wrap"><div class="grid three">'+panel("Customer account","View personal bookings, payment statements, signed documents and case history after verified authentication.",'<span class="status">Not enabled</span>')+panel("Staff & compliance","MFA-protected RBAC, confidential dispute evidence and case review.",'<span class="status">Not enabled</span>')+panel("Digital signature","Verified recipients and tamper-evident signer records only after the signing provider is integrated.",'<span class="status">Not enabled</span>')+'</div><div class="alert" style="margin-top:26px">Access intentionally closed. This website does not issue passwords, claim OAuth login, or reveal customer data before secure identity-provider provisioning.</div>'+link("/security","Read release gates","btn btn-wine")+'</div></section>';}
function render(path){switch(path){case "/about":return about();case "/contact":return contact();case "/refund-policy":return policy();case "/access":return access();case "/reviews":case "/feedback":case "/complaints":case "/disputes":return serviceForm(path.slice(1));default:return "";}}
function init(path){if(!["/reviews","/feedback","/complaints","/disputes"].includes(path))return;
var f=document.getElementById("care-intake"),copy=document.getElementById("copy-case"),status=document.getElementById("care-result"),draft="";
f.addEventListener("submit",function(event){event.preventDefault();
if(!f.reportValidity())return;
var kind=f.dataset.kind,topic=document.getElementById("case-type").value,ref=document.getElementById("case-ref").value.trim(),description=document.getElementById("case-description").value.trim();
if(description.length<15||description.length>3000)return;
draft="R-Rent "+kind.toUpperCase()+"\nCategory: "+topic+"\nReference: "+(ref||"Not provided")+"\n"+(kind==="disputes"?"Disputed USD: "+(document.getElementById("case-amount").value||"Not specified")+"\nTransaction date: "+(document.getElementById("case-date").value||"Not specified")+"\n":"")+"Details:\n"+description+"\n\nSubmitted by: [complete in email program]";
copy.disabled=false;status.textContent="Draft prepared. Your email application will open if supported. Review the recipient and send yourself; no case has been filed automatically.";
var subject="R-Rent "+kind+" — "+topic;
var url="mailto:"+receiver+"?subject="+encodeURIComponent(subject)+"&body="+encodeURIComponent(draft);
if(url.length<=1900){window.location.href=url;}else{status.textContent="Request prepared. Copy the text and paste it into a new email to "+receiver+"; no case has been filed automatically.";}
});
copy.addEventListener("click",function(){if(!draft)return;if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(draft).then(function(){status.textContent="Draft copied. Send it using your email application to create an actual request.";}).catch(function(){status.textContent="Copy unavailable in this browser. Use your email program to prepare the request.";});}});
}
window.RRentCare={routes:routes,render:render,init:init};
})();
