(function(){
"use strict";
const data={
 trail:{name:"2026 Chevrolet Trailblazer",slug:"trailblazer-2026",rate:"$59.00/day",description:"A versatile five-seat compact SUV for errands, local travel and longer trips. Chevrolet's 2026 lineup offers a standard 1.2-liter turbocharged three-cylinder powertrain and an available 1.3-liter turbocharged engine. Confirm the exact trim and installed equipment on the assigned vehicle before contracting.",specs:[["Seats","5"],["Engine choices","1.2L turbo I3 (137 hp) / available 1.3L turbo I3 (155 hp)"],["Transmission","Automatic (CVT with FWD; 9-speed automatic with AWD configuration)"],["Drivetrain","FWD standard; AWD available"],["Display","11-inch touchscreen standard"],["Phone compatibility","Wireless Apple CarPlay and Android Auto compatibility"],["Safety","Chevy Safety Assist standard, including forward collision alert, automatic emergency braking and lane keeping assistance"],["Utility","Fold-flat front passenger seat; available liftgate upgrades"],["Dimensions","Approx. 174 in. long × 71 in. wide; height varies by drivetrain"],["Fuel economy","Up to EPA-estimated 31 mpg combined with available 1.3L FWD; actual vehicle varies"]],source:"https://www.chevrolet.com/suvs/trailblazer",notice:"These are Chevrolet model-year specifications. The listed vehicle's exact trim, drivetrain, mileage, exterior color and individual options have not been independently verified."},
 bronco:{name:"2026 Ford Bronco Sport Big Bend",slug:"bronco-sport-2026",rate:"$89.99/day",description:"The Bronco Sport Big Bend combines everyday usability with standard 4×4 traction and adaptable drive modes. Its 1.5-liter EcoBoost turbo engine, 8-speed automatic transmission and practical compact SUV layout support a mix of city and leisure travel.",specs:[["Seats","Up to 5"],["Engine","1.5L EcoBoost turbocharged three-cylinder"],["Power","180 hp / 200 lb-ft torque (Ford published rating)"],["Transmission","8-speed automatic"],["Drivetrain","Standard 4×4"],["Drive settings","Five G.O.A.T. Modes: Normal, Eco, Sport, Slippery and Off-Road"],["EPA estimate","25 city / 30 highway mpg for 1.5L 4×4 (individual vehicle/conditions vary)"],["Wheelbase","105.1 in."],["Length","173.1 in."],["Width","74.3 in. excluding mirrors"],["Fuel capacity","16 gallons"],["Towing","Up to 2,200 lb with available Class II towing package; rental towing use subject to contract"]],source:"https://www.ford.com/suvs/bronco-sport/models/big-bend/",notice:"Ford model-year Big Bend specifications are not proof of installed packages. Confirm exact options, condition and authorized activities for the rental unit."}
};
function esc(x){return String(x).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");}
function specsHtml(key){const m=data[key];if(!m)return "";return '<section class="specs-panel"><h2>Vehicle specifications</h2><p>'+esc(m.description)+'</p><div class="spec-grid">'+m.specs.map(x=>'<div class="spec-entry"><dt>'+esc(x[0])+'</dt><dd>'+esc(x[1])+'</dd></div>').join("")+'</div><p class="subtle">'+esc(m.notice)+'</p><a href="'+esc(m.source)+'" target="_blank" rel="noopener noreferrer" class="spec-source">View manufacturer specifications ↗</a></section>';}
function gatesHtml(){return '<section class="rental-gates"><h2>Rental application &amp; authorization stages</h2><p>Start with a preliminary quote. A confirmed booking is not available until the following independent production gates are active and verified.</p><ol class="gates-grid"><li><strong>01 · Quote</strong><span>Choose vehicle, duration and optionally estimate the proposed $9/day coverage line.</span><b class="gate-ready">Public estimate available</b></li><li><strong>02 · Identity</strong><span>Authenticated driver record and license eligibility verification.</span><b>Protected verification unavailable</b></li><li><strong>03 · Insurance</strong><span>Carrier/underwriter validation; $9/day is not bound protection.</span><b>Insurance program approval pending</b></li><li><strong>04 · Agreements</strong><span>Approved contract, disclosure elections, consent and verified e-signature.</span><b>Execution unavailable</b></li><li><strong>05 · Payment</strong><span>Final lawful tax/fees, PCI-hosted checkout, fraud screening and signed webhook evidence.</span><b>Settlement unavailable</b></li><li><strong>06 · Release</strong><span>Human approval, paid invoice, confirmed insurance and vehicle inspection.</span><b>Handoff unavailable</b></li></ol><p class="notice">No application, uploaded document, coverage election or payment is accepted through the public estimator. Sensitive driver information must never be entered in open text or emailed.</p></section>';}
window.RRentFleet={data,specsHtml,gatesHtml};
})();